services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: yara
      POSTGRES_PASSWORD: yara
      POSTGRES_DB: yara_cms
    ports:
      - "5432:5432"
    volumes:
      - yara_cms_pg:/var/lib/postgresql/data
volumes:
  yara_cms_pg:
