/** Visual alt text keyed by path under /uploads/. No suburb claims. */

export const FILE_ALTS = {
  "2025/07/P1-1.jpg": "Kitchen with black marble island, gold stools and white cabinetry",
  "2025/07/P1-2.jpg": "Cluster of teardrop glass pendant lights with textured metal caps",
  "2025/07/P1-33.jpg": "Hallway with chevron timber floor, white panelling and black pendants",
  "2026/03/P2-1.jpg": "Donia Yara seated in a light armchair by a window",
  "2025/07/P4-1.jpg": "Woman reflected in a curved mirror in a softly lit dressing area",
  "2025/07/testimonial.jpg": "Living space with sculptural gold-framed mirror and herringbone timber floor",
  "2025/07/ONLY-Donia-Yara-W-no-dot-1-scaled.png": "Donia Yara",
  "2025/07/about-us2.jpg": "Living room with magnolia branches on a marble table and arched windows",
  "2025/07/about-us-down.jpg": "Dining room with round black table, white chairs and magnolia branches",
  "2025/07/P5-3.jpg": "Donia Yara",
  "2025/07/p6-1our-vision-Left-photo.jpg": "Hallway with organic stone sculpture, dark timber panelling and stacked stone wall",
  "2025/07/p6-2our-mission-middle-photo.jpg": "Coiled polished metal ribbon sculpture on a light wall",
  "2025/07/P6-3our-values-right-photo.jpg": "Cascading crystal chandelier above a textured bronze rock basin",
  "2025/07/Untitled-2-1.png": "Illustrated interior design process diagram",
  "2025/07/P15-1.jpg": "Material mood board with marble, fabric, timber and white florals",
  "2025/07/P15-2.jpg": "Ceramic vases and coffee table books on a timber surface",
  "2025/07/P7-2.jpg": "Living room with curved sofa, sculptural lighting and layered textures",
  "2025/07/P8-1.jpg": "Open living interior with refined furnishings and warm lighting",
  "2025/07/P8-2.jpg": "Styled interior details with curated finishes and decorative objects",
  "2025/07/our-services-banner.jpg": "Interior design services banner",
  "2025/07/P15-3.jpg": "Pottery Barn",
  "2025/07/P15-4.jpg": "West Elm",
  "2025/07/P15-5.jpg": "Coco Republic",
  "2025/07/P15-6.jpg": "Provincial Home Living",
  "2025/07/P15-7.jpg": "Freedom",
  "2025/07/adairs-b-4.png": "Adairs",
  "2025/07/adairs-w-5.png": "Adairs",
  "2025/07/png-koala111B.png": "Koala",
  "2025/07/png-koala111white.png": "Koala",
  "2025/07/png-pottery-white-1-scaled.png": "Pottery Barn",
  "2025/07/png-west-elm-white-scaled.png": "West Elm",
  "2025/07/png-provincial-white-scaled.png": "Provincial Home Living",
  "2025/07/png-coco-white-scaled.png": "Coco Republic",
  "2025/07/png-freedom-white-scaled.png": "Freedom",
  "brand/partners/P15-3.png": "Pottery Barn",
  "brand/partners/P15-4.png": "West Elm",
  "brand/partners/P15-5.png": "Coco Republic",
  "brand/partners/P15-6.png": "Provincial Home Living",
  "brand/partners/P15-7.png": "Freedom",
  "brand/partners/adairs-b-4.png": "Adairs",
  "brand/partners/adairs-w-5.png": "Adairs",
  "brand/partners/png-koala111B.png": "Koala",
  "brand/partners/png-koala111white.png": "Koala",
  "brand/partners/png-pottery-white-1-scaled.png": "Pottery Barn",
  "brand/partners/png-west-elm-white-scaled.png": "West Elm",
  "brand/partners/png-provincial-white-scaled.png": "Provincial Home Living",
  "brand/partners/png-coco-white-scaled.png": "Coco Republic",
  "brand/partners/png-freedom-white-scaled.png": "Freedom",
  "brand/interior-design-process-illustration.webp": "Illustrated interior design process diagram",
  "brand/yara-luxe-interiors-logo.png": "Yara Luxe Interiors",
  "brand/yara-luxe-social-1200x630.jpg": "Interior designer reviewing material and colour samples",

  "2026/04/22-3.jpg": "Stone mansion at dusk with a patio fire pit and outdoor lounge furniture",
  "2026/01/Blog-5.jpg": "Foyer with under-lit marble stair, gold sculpture and branch chandelier",
  "2026/02/11.jpg": "Dark home office with arched windows and illuminated black cabinetry",
  "2026/03/44-2.jpg": "Charcoal kitchen with marble island, gold pendants and velvet chairs",
  "2025/11/3-2.jpg": "White mansion with black-framed arches, stone terrace and swimming pool",
  "2026/01/Blog-3.jpg": "White living room with fireplace, arched window and winter landscape beyond",
  "2026/01/blog-2.jpg": "Kitchen with waterfall marble island, globe pendants and lit open shelves",
  "2025/08/15.jpg": "Open-plan kitchen with black island, white cabinetry and garden windows",
  "2025/07/14-1.jpg": "Concrete stair and gold-textured glass wall in a sculptural interior",
  "2025/07/13-1.jpg": "Dark living space with sculptural lounge chairs and metallic wall art",
  "2025/07/Moody-Glam-2-1.jpg": "Bedroom with arched black-framed windows, low bed and landscape artwork",
  "2025/07/11-2.jpg": "Foyer with brass console, disc chandelier and fluted wall panelling",
  "2025/07/download-45.jpg": "Curved stone staircase in a panelled foyer with wall sconces",
  "2025/06/How-to-Layer-Light-Like-a-Designer-.jpg": "Kitchen island with waterfall marble, gold stools and layered lighting",
  "2025/06/3D-Rendering-in-Interior-Design.jpg": "Living room with silver branch wall sculpture, cream sofas and chandelier",
  "2025/05/Design-blog.jpg": "Grey living room with sectional sofa, abstract art and charcoal tables",
  "2025/04/blog-cohesive.jpg": "Living room with black grand piano, carved stone fireplace and tall windows",
  "2025/03/Top-10-Tips-for-Designing-a-Timeless-Kitchen-1.jpg": "Kitchen with veined marble island, spherical pendants and dark cabinetry",

  "2026/06/Interior-Design-Excellence.webp": "Living room with grey sofa, sequined cushions, black bookshelf and gold artwork",
  "2026/06/Interior-design-for-living-room.webp": "Living room with curved cream sofa, gold cushions and mirrored coffee tables",
  "2026/06/full-home-interior-design-services-.webp": "Designer reviewing a portfolio on a tufted chaise longue",
  "2026/06/home-interior-design.webp": "Console vignette with sculptural lamp, arched mirror and gold objects",
  "2026/06/Full-Home-Renovation.webp": "Gold side tables styled with sculptural objects and a white decorative box",
  "2026/06/Full-Home-Interior-Design-Melbourne.webp": "Styled timber bookshelf with a trailing plant and gold ornament",
  "2026/06/Modern-Interior-Design-for-Contemporary-Homes.webp": "Interior designer holding material and colour samples in front of a bookshelf",
  "2026/06/Modern-Interior-Design.webp": "Contemporary interior with layered lighting and neutral furnishings",
  "2026/06/luxury-home-interior-design-Melbourne-company.webp": "Luxury living interior with custom furnishings and warm lighting",
  "2026/06/Luxury-Home-Interior-Design-Melbourne.webp": "Luxury home interior with refined finishes and layered lighting",
  "2026/06/Luxury-commercial-interior-design-melbourne.webp": "Showroom reception with marble desk, lounge seating and studio branding",
  "2026/06/commercial-interior-design-near-me.webp": "Commercial interior with custom joinery and reception seating",
  "2026/06/commercial-interior-design.webp": "Commercial interior with stone surfaces and contemporary furniture",
  "2026/06/Hospitality-interior-design-Melbourne.webp": "Hospitality interior with lounge seating and warm ambient lighting",
  "2026/06/Best-interior-designers-Melbourne-1.webp": "Office interior with custom desk and contemporary finishes",
  "2026/06/Interior-design-services-Melbourne.webp": "Retail interior with display joinery and refined lighting",
  "2026/06/Affordable-interior-designers-Melbourne-1.webp": "Hospitality lounge with upholstered seating and decorative lighting",
  "2026/06/interior-design-for-commercial.webp": "Commercial reception area with stone counter and lounge furniture",
  "2026/06/commercial-office-interior-design.webp": "Office interior with workstations and contemporary joinery",
  "2026/06/Small-commercial-interior-design-melbourne.webp": "Compact commercial interior with custom joinery",
  "2026/06/residential-interior-design.webp": "Residential living interior with tailored furniture and lighting",
  "2026/06/interior-design-residential.webp": "Residential interior with layered finishes and natural light",
  "2026/06/Best-residential-interior-design-melbourne.webp": "Residential living space with sofa, artwork and custom styling",
  "2026/06/Affordable-interior-designers-Melbourne.webp": "Home interior with neutral furnishings and decorative lighting",
  "2026/06/Best-interior-designers-Melbourne.webp": "Modern home interior with tailored furniture",
  "2026/06/Affordable-residential-interior-design-melbourne.webp": "Residential interior with warm finishes and custom joinery",
  "2026/06/interior-design-for-residential-house.webp": "Family living interior with sofa and layered lighting",
  "2026/06/Residential-interior-design-melbourne-cost.webp": "Residential interior with stone, timber and upholstered furniture",
  "2026/06/residential-interior-design-companies.webp": "Home interior with custom cabinetry and lighting",
  "2026/06/Small-residential-interior-design-melbourne.webp": "Compact residential interior with efficient furniture layout",
  "2026/06/kitchen-interior-design.webp": "Designer standing in a cream kitchen with marble island and gold hardware",
  "2026/06/kitchen-interior-designer-melbourne.webp": "Kitchen interior with stone benches and custom cabinetry",
  "2026/06/kitchen-interior-design-ideas.webp": "Kitchen with island seating and layered pendant lighting",
  "2026/06/kitchen-designers-melbourne.webp": "Kitchen interior with cabinetry and stone surfaces",
  "2026/06/kitchen-renovation-melbourne.webp": "Renovated kitchen with island and integrated appliances",
  "2026/06/kitchen-remodelling-melbourne.webp": "Kitchen remodel with stone benches and custom joinery",
  "2026/06/melbourne-kitchen-renovations.webp": "Kitchen with island, cabinetry and statement lighting",
  "2026/06/kitchen-renovations-in-melbourne.webp": "Kitchen interior with stone island and tall cabinetry",
  "2026/06/best-kitchen-renovations-melbourne.webp": "Kitchen with functional island layout and premium finishes",
  "2026/06/kitchen-renovations-melbourne.webp": "High-spec kitchen with stone surfaces and custom cabinetry",
  "2026/06/bathroom-interior-designer-melbourne.webp": "Bathroom with stone vanity and contemporary fixtures",
  "2026/06/luxury-bathroom-interior-design.webp": "Bathroom with stone surfaces and statement lighting",
  "2026/06/bathroom-renovation-interior-designer-melbourne.webp": "Renovated bathroom with stone finishes and glass shower",
  "2026/06/bathroom-interior.webp": "Bathroom interior with vanity, mirror and stone surfaces",
  "2026/06/bathroom-interior-designer.webp": "Bathroom with custom vanity and warm lighting",
  "2026/06/bathroom-interior-designers.webp": "Bathroom interior with stone and metallic finishes",
  "2026/06/modern-bathroom-interior-design.webp": "Modern bathroom with clean-lined vanity and glass shower",
  "2026/06/small-bathroom-interior-design.webp": "Compact bathroom with space-efficient vanity and stone finishes",
  "2026/06/interior-designer-for-bathroom-remodel.webp": "Bathroom remodel with stone vanity and refined fixtures",
  "2026/06/bathroom-interior-design.webp": "Bathroom with layered lighting, stone surfaces and timber details",
  "2026/06/color-consultation-interior-design.webp": "Material and colour samples arranged for an interior consultation",
  "2026/06/interior-design-consultation-australia.webp": "Interior consultation setting with samples and furnishings",
  "2026/06/interior-design-initial-consultation.webp": "Consultation setting with material boards and interior finishes",
  "2026/06/online-consultation-interior-design.webp": "Interior samples and finishes prepared for a design consultation",
  "2026/06/interior-design-consultation-price.webp": "Styled interior used during a design consultation",
  "2026/06/interior-design-consultation-services.webp": "Consultation interior with furniture and material palettes",
  "2026/06/colour-consultation-interior-design.webp": "Colour and fabric samples for an interior palette",
  "2026/06/interior-design-onsite-consultation.webp": "On-site interior with furnishings prepared for consultation",
  "2026/06/interior-design-consultation.webp": "Interior consultation space with samples and seating",
  "2026/06/new-build-interior-design.webp": "New home interior with open living space and contemporary finishes",
  "2026/06/New-Build-Banner.webp": "New-build interior with architectural lighting and clean lines",
  "2026/06/interior-design-for-new-build-homes.webp": "New home living interior with custom joinery",
  "2026/06/interior-design-ideas-for-new-build-homes.webp": "New-build interior with tailored furniture and lighting",
  "2026/06/new-build-interior.webp": "New home interior with stone, timber and neutral furnishings",
  "2026/06/interior-design-new-build-homes.webp": "New-build living space with contemporary furniture",
  "2026/06/new-build-home-interior-design.webp": "New home interior with custom cabinetry and lighting",
  "2026/06/new-build-interior-designers.webp": "New-build interior with open-plan living and refined finishes",
  "2026/06/new-build-flat-interior-design.webp": "Apartment interior with efficient layout and custom joinery",
  "2026/06/new-build-homes-interior-design.webp": "New home interior showing living and dining finishes",
  "2026/06/supervision1.webp": "Interior under construction with finishes being installed",
  "2026/06/supervisionBanner.webp": "Project interior during fit-out and finishing",
  "2026/06/supervision2.webp": "Site interior showing joinery and finish installation",
  "2026/06/supervision3.webp": "Interior fit-out with trades coordinating finishes",
  "2026/06/supervision4.webp": "Near-complete interior with lighting and joinery in place",
  "2026/06/supervision5jpg.webp": "Supervised interior project with installed furnishings",
  "2026/06/supervision6.webp": "Interior detailing during project supervision",
  "2026/06/supervision7.webp": "Finished interior space after project coordination",
  "2026/06/supervision8.webp": "Interior showing installed cabinetry and lighting",
  "2026/06/supervision9.webp": "Project interior with completed joinery and styling",
  "2026/06/supervision10.webp": "Completed interior after supervised installation"
};

export function fileAlt(src, fallback = "") {
  const key = String(src)
    .replace(/^\/uploads\//, "")
    .replace(/^uploads\//, "");
  return FILE_ALTS[key] || fallback;
}

export const BLOG_IMAGE_ALTS = {
  "2026/04/22-3.jpg": FILE_ALTS["2026/04/22-3.jpg"],
  "2026/01/Blog-5.jpg": FILE_ALTS["2026/01/Blog-5.jpg"],
  "2026/02/11.jpg": FILE_ALTS["2026/02/11.jpg"],
  "2026/03/44-2.jpg": FILE_ALTS["2026/03/44-2.jpg"],
  "2025/11/3-2.jpg": FILE_ALTS["2025/11/3-2.jpg"],
  "2026/01/Blog-3.jpg": FILE_ALTS["2026/01/Blog-3.jpg"],
  "2026/01/blog-2.jpg": FILE_ALTS["2026/01/blog-2.jpg"],
  "2025/08/15.jpg": FILE_ALTS["2025/08/15.jpg"],
  "2025/07/14-1.jpg": FILE_ALTS["2025/07/14-1.jpg"],
  "2025/07/13-1.jpg": FILE_ALTS["2025/07/13-1.jpg"],
  "2025/07/Moody-Glam-2-1.jpg": FILE_ALTS["2025/07/Moody-Glam-2-1.jpg"],
  "2025/07/11-2.jpg": FILE_ALTS["2025/07/11-2.jpg"],
  "2025/07/download-45.jpg": FILE_ALTS["2025/07/download-45.jpg"],
  "2025/06/How-to-Layer-Light-Like-a-Designer-.jpg": FILE_ALTS["2025/06/How-to-Layer-Light-Like-a-Designer-.jpg"],
  "2025/06/3D-Rendering-in-Interior-Design.jpg": FILE_ALTS["2025/06/3D-Rendering-in-Interior-Design.jpg"],
  "2025/05/Design-blog.jpg": FILE_ALTS["2025/05/Design-blog.jpg"],
  "2025/04/blog-cohesive.jpg": FILE_ALTS["2025/04/blog-cohesive.jpg"],
  "2025/03/Top-10-Tips-for-Designing-a-Timeless-Kitchen-1.jpg": FILE_ALTS["2025/03/Top-10-Tips-for-Designing-a-Timeless-Kitchen-1.jpg"]
};

export function blogImageAlt(post) {
  if (post?.featuredImageAlt) return post.featuredImageAlt;
  return BLOG_IMAGE_ALTS[post.img] || fileAlt(post.img, "Interior design photograph");
}

export const SERVICE_OG_IMAGE = {
  "/residential-interior-design-melbourne": "/uploads/2026/06/residential-interior-design.webp",
  "/commercial-interior-design-melbourne": "/uploads/2026/06/Luxury-commercial-interior-design-melbourne.webp",
  "/kitchen-interior-design-melbourne": "/uploads/2026/06/kitchen-interior-design.webp",
  "/bathroom-interior-design-melbourne": "/uploads/2026/06/bathroom-interior-designer-melbourne.webp",
  "/interior-design-consultation-melbourne": "/uploads/brand/yara-luxe-social-1200x630.jpg",
  "/new-build-interior-design-melbourne": "/uploads/2026/06/new-build-interior-design.webp",
  "/interior-design-project-supervision-melbourne": "/uploads/2026/06/supervision1.webp",
  "/full-home-interior-design-melbourne": "/uploads/2026/06/Full-Home-Interior-Design-Melbourne.webp"
};

export const SIZES = {
  logo: "180px",
  feature: "(max-width: 768px) 92vw, 350px",
  aboutPhoto: "(max-width: 900px) 92vw, 520px",
  testimonial: "(max-width: 900px) 100vw, 50vw",
  dreams: "100vw",
  partner: "160px",
  portfolio: "(max-width: 700px) 50vw, (max-width: 1100px) 25vw, 280px",
  blogCard: "(max-width: 768px) 100vw, 560px",
  blogFeatured: "(max-width: 900px) 100vw, 780px",
  blogThumb: "75px",
  avatar: "132px",
  drawer: "120px",
  contentCol: "(max-width: 900px) 100vw, 900px",
  galleryStrip: "(max-width: 700px) 50vw, (max-width: 1100px) 33vw, 20vw",
  processPhoto: "(max-width: 900px) 100vw, 480px",
  homeSvc: "(max-width: 767px) 92vw, (max-width: 1024px) 46vw, 280px"
};
